### ISSUE TITLE
Leading space check: Doesn't check tab character

### ISSUE THREAD

**Issue by mgrachev** [mgrachev/dotenv-linter#56]
Need to fix this bug and write a test for this case.

Link: https://github.com/mgrachev/dotenv-linter/blob/master/src/checks/leading_space.rs#L18

**Comment by mstruebing** [comment]
While at it, I think it would be good to check if the line starts with anything else than `[a-zA-Z#]`, the `#` because of comments.

**Comment by mgrachev** [comment]
@mstruebing We already skip comments https://github.com/mgrachev/dotenv-linter/blob/master/src/checks.rs#L54

Could you give more examples [there](https://github.com/mgrachev/dotenv-linter/issues/23)?

**Comment by mstruebing** [comment]
I mean, to only check if it starts also with a tab-character can lead to additional things which are not really wanted. I.e what if the line would be: `*HELLO=abc` - would that be a valid line?
I assume that is an error, so I mean that it would be better to chack that the line starts with a valid character instead of checking every character which isn't allowed. That could be easily done with a regex ala `[A-Z]` - since it needs to be an uppercase letter.

That would make sure a line never starts with a space, tab or any other unallowed character.

**Comment by mgrachev** [comment]
@mstruebing I like the idea of checking valid characters instead of invalid characters, but I wouldn’t like to use regexp to do that.

I think we can use the standard library of Rust. For example:
```rust
line.raw_string.starts_with(|c: char| c.is_alphabetic() || c == '_')
```

**Comment by mgrachev** [comment]
The example above covers all of these cases:
```
// FOO=BAR => None
// _FOO=BAR => None
// .FOO=BAR => Warning
// *FOO=BAR => Warning
// 1FOO=BAR => Warning
// <tab>FOO=BAR => Warning
// <space>FOO=BAR => Warning
```
